/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        border: "var(--border)",
        "border-light": "var(--border-light)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        ring: "var(--ring)",

        nvidia: { DEFAULT: "var(--nv)", bright: "var(--nv-bright)" },
        dell: { DEFAULT: "var(--dell)", bright: "var(--dell-bright)" },
        clay: "var(--clay)",
        sun: "var(--sun)",
        berry: "var(--berry)",
        cloud: "var(--dell-bright)",

        ink: "var(--background)",
        panel: "var(--card)",
        panel2: "var(--muted)",
        line: "var(--border)",
        lineSoft: "var(--border-light)",
        text: "var(--foreground)",
        dim: "var(--muted-foreground)",
        faint: "var(--faint)",
        danger: "var(--berry)",
        warn: "var(--sun)",
      },
      fontFamily: {
        display: ['"Fraunces"', "ui-serif", "Georgia", "serif"],
        serif: ['"Fraunces"', "ui-serif", "Georgia", "serif"],
        sans: ['"Nunito"', "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ['"JetBrains Mono"', "ui-monospace", "monospace"],
      },
      borderRadius: {
        none: "0",
        DEFAULT: "1rem",
        sm: "0.75rem",
        md: "1rem",
        lg: "1.25rem",
        xl: "1.5rem",
        "2xl": "2rem",
        "3xl": "2.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
